networks:
  currencies-network:
    driver: bridge

services:
  app:
    container_name: currencies-backend
    build:
      context: .
      dockerfile: CurrencyExchange/Dockerfile
    ports:
      - "80:80"
    networks:
      - currencies-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: "currencies"
      POSTGRES_USER: "alexpg"
      POSTGRES_PASSWORD: ${password}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - currencies:/var/lib/postgresql/data
    ports:
      - "5432"
    networks:
      - currencies-network

volumes:
  currencies:
