# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: build image
        run: docker build . -t alexhiems/currencyexchange:latest
      - name: push image to docker hub
        run: |
          docker login -u alexhiems -p ${{ secrets.DOCKERHUB }}
          docker push alexhiems/currencyexchange:latest
